# Generated by Django 4.2.4 on 2023-09-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'instrumental'), (2, 'lyrics'), (3, 'vocal'), (4, 'mix'), (5, 'done')], default=0, max_length=255),
        ),
    ]
