# Generated by Django 4.2.4 on 2023-10-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_queryparamssample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('songs', models.ManyToManyField(to='core.song')),
            ],
        ),
    ]
