# Generated by Django 4.2.4 on 2023-10-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
