# Generated by Django 4.2.4 on 2023-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegauser',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
