# Generated by Django 4.2.4 on 2023-08-31 20:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255, null=True)),
                ('era', models.CharField(max_length=255, null=True)),
                ('mood', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('audio', models.URLField()),
                ('cover', models.URLField()),
                ('lyrics', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('query_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.queryparams')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('query_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.queryparams')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('none', 'none'), ('instrumental', 'instrumental'), ('lyrics', 'lyrics'), ('vocal', 'vocal'), ('mix', 'mix'), ('done', 'done')], default='none', max_length=255)),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
        ),
    ]
