# Generated by Django 4.2.4 on 2023-10-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_song_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParamsSample',
            fields=[
                ('queryparams_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.queryparams')),
                ('title', models.CharField(max_length=255, null=True)),
                ('cover', models.URLField()),
            ],
            bases=('core.queryparams',),
        ),
    ]
